### ISSUE TITLE
Change edit Nethash

### ISSUE THREAD

**Issue by mastah12322** [ArkEcosystem/platform-sdk#1042]
Hi , i have reinstaled the arc on my server, my question is can i set a custom nethash ? the old ? or this is not posibil ??

Thanks

**Expected Behavior**

**Current Behavior**

**Possible Solution**

**Steps to Reproduce (for bugs)**

**Context**

**Your Environment**

- Version used:
- Environment name and version (e.g. node.js v10.15.3):
- Server type and version:
- Operating System and version:
- Link to your project:

**Comment by mastah12322** [comment]
Hi , i have reinstaled the arc on my server, my question is can i set a custom nethash ? the old ? or this is not posibil ??

Thanks

**Comment by boldninja** [comment]
Answered you here: https://github.com/ArkEcosystem/core/issues/4296#issuecomment-781337302
