### ISSUE TITLE
Cardano

### ISSUE THREAD

**Issue by electic** [ArkEcosystem/platform-sdk#1595]
Hi, I noticed you use the cardano serialization nodejs package and wanted to check here and see if you where having issues with webpack 5 trying to bundle it?

**Comment by faustbrian** [comment]
We don't use webpack so can't comment on that.

**Comment by electic** [comment]
Ah, I noticed you were using on your wallet with webpack and commented it out. Perhaps I will ask there. Thanks anyway!
