### ISSUE TITLE
Implement an amount sanitizer

### ISSUE THREAD

**Issue by luciorubeens** [ArkEcosystem/platform-sdk#442]
Format the value that the user entered according to their locale to a valid javascript format.

- Should handle decimal digits (8 digits for cryptos and 0 or 2 for fiat)
- Should handle group and decimal separators (dot, comma, whitespace?)
- Should only allow numbers

```
0,0001 -> 0.0001
45,210.21 -> 45210.21
45.210,21 -> 45210.21
0.100000008123 -> 0.10000000
52,21579 -> 52.21
```

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/platform-sdk/commit/ed20a90bebc8a8109abe46ca99a8bacdf9256282
